### ISSUE TITLE
Editing the touch controls

### ISSUE THREAD

**Issue by 44cK3r** [Vera-Firefly/PojavLauncher-Beta-Zink#2]
I can't remove the touch controls at the top I want to get rid of all the ones in a different language I can't read them so I don't want them sorry Love You Keep It Up And Stay Positive

**Comment by Vera-Firefly** [comment]
> I can't remove the touch controls at the top I want to get rid of all the ones in a different language I can't read them so I don't want them sorry Love You Keep It Up And Stay Positive

Sorry,I will solve
